### 소프트맥스 함수

In [3]:
import numpy as np
a=np.array([0.3,2.9,4.0])
exp_a=np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [7]:
sum_exp_a=np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [9]:
y=exp_a/sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [11]:
#함수 정의
def softmax(a):
    exp_a=np.exp(a)
    sum_exp_a=np.sum(exp_a)
    y=exp_a/sum_exp_a
    return y

In [13]:
# overflow 방지
a=np.array([1010,1000,990])
np.exp(a)/np.sum(np.exp(a))

C:\Users\un747\AppData\Local\Temp\ipykernel_5648\351173439.py:3: RuntimeWarning: overflow encountered in exp
  np.exp(a)/np.sum(np.exp(a))
C:\Users\un747\AppData\Local\Temp\ipykernel_5648\351173439.py:3: RuntimeWarning: invalid value encountered in divide
  np.exp(a)/np.sum(np.exp(a))


array([nan, nan, nan])

In [17]:
c=np.max(a)
a-c
np.exp(a-c)/np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [19]:
def softmax(a):
    c=np.max(a)
    exp_a=np.exp(a-c)
    sum_exp_a=np.sum(exp_a)
    y=exp_a/sum_exp_a
    return y

In [21]:
a=np.array([0.3,2.9,4.0])
y=softmax(a)
print(y)
np.sum(y) # 출력의 총 합이 1이 됨

[0.01821127 0.24519181 0.73659691]


1.0

In [29]:
#데이터셋 가져와야함
#import sys, os
#sys.path.append(os.pardir)
#from dataset.mnist import load_mnist

#(x_train, t_train), (x_test, t_test) = \load_mnist(flatten=True, normalize=False)

#print(x_train.shape)
#print(t_train.shape)
#print(x_test.shape)
#print(t_test.shape)

In [31]:
#데이터셋 필요
#import sys, os
#sys.path.append(os.pardir)
#import numpy as np
#from dataset.mnist import load_mnist
#from PILimport Image

#def img_show(img):
#   pil_img=Image.fromarray(np.unit8(img))
#   pil_img.show()

#(x_train, t_train), (x_test, t_test) = \load_mnist(flatten=True, normalize=False)

#img=x_train[0]
#label=t_train[0]
#print(label)

#print(img.shape)
#img=img.reshape(28,28)
#print(img.shape)

#img_show(img)

In [33]:
#def get_data():
#    (x_train,t_train), (x_test, t_test)=\load_mnist(normalize=True, flatten=True, one_hot_label=False)
#    return x_test, t_test

#def init_network():
#    with open("sample_weight.pkl", 'rb') as f:
#        network=pickle.load(f)

#    return network

#def predict(network, x):
#    w1, w2, w3=network['w1'], network['w2'], network['w3']
#    b1, b2, b3=network['b1'], network['b2'], network['b3']

#    a1=np.dot(x,w1) + b1
#    z1=sigmoid(a1)
#    a2=np.dot(z1,w2) + b2
#    z2=sigmoid(a2)
#    a3=np.dot(z2,w3) + b3
#    y=softmax(a3)

#    return y

In [37]:
#x, t = get_data()
#network= init_netowrk()

#accuracy_cnt=0
#for i in range(len(x)):
#    y=predict(network, x[i])
#    p=np.argmax(y)
#    if p==t[i]:
#        accuracy_cnt+=1

#print("Accuracy:" + str(float(accuracy_cnt)/len(x))

### 배치 처리

In [42]:
#x, _ = get_data()
#network=init_network()
#w1, w2, w3 = network['w1'], network['w2'], network['w3']

#x.shape
#x[0].shape
#w1.shape
#w2.shape
#w3.shape

In [44]:
#x, t= get_data()
#network=init_network()

#batch_size=100
#accuracy_cnt=0

#for i in range(0, len(x), batch_size):
#    x_batch=x[i:i+batch_size]
#    y_natch=predict(network, x_batch)
#    p=np.argmax(y_batch, axis=1)
#    accuracy_cnt+=np.sum(p==t[i:i+batch_size])

#print("Accuracy:" + str(float(accuracy_cnt/len(x))

In [50]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
list(range(0,10,3))

[0, 3, 6, 9]

In [54]:
x=np.array([[0.1,0.8,0.1],[0.3,0.1,0.6],[0.2,0.5,0.3],[0.8,0.1,0.1]])
y=np.argmax(x,axis=1)
print(y)

[1 2 1 0]


In [56]:
y=np.array([1,2,1,0])
t=np.array([1,2,0,0])
print(y==t)
np.sum(y==t)

[ True  True False  True]


3